### PR TITLE
Yuji RiderNavBar Updates

### LINKED ISSUE #9: BUG: Rider can see tabs in navbar they cant/shouldnt access
### Summary

A user with ONLY a rider role should not be able to see field relevant to other roles and only ride request should be available to them, but right now they can see a dropdown for `Shifts` and `Drivers Page`

### Expected Behavior

The user should only see the dropdown for `Ride Request`

### Current / Observed Behavior

image

### Steps to Reproduce

1. Log in as user with no roles
2. Get your role toggled by an admin to be a rider
3. View navbar

Implementation Todo:

- [x] Edit `AppNavbar.js` and make sure that the tabs are not available to riders

### PR DESCRIPTION
**Pull request by yuji-sakaguchi**
Fixed bug where not riders can access dropdown for Shifts and Drivers Page button on the navbar. 
Made changes to the test file to make sure shifts and drivers page navbar buttons are hidden for riders. 

Extra: 
Made additional edits to navbar for adminOnly users so all the required information is shown.
Made sure admin users with multiple roles won't have duplicate navbar buttons.

Dokku Deployment: https://proj-gauchoride-yuji-sakaguchi-dev.dokku-14.cs.ucsb.edu/

Closes #9 

New Riders User (No more Shifts, Drivers Page)
image

New AdminOnly User (Added Shifts Availability as part of Shifts Dropdown, Drivers Page)
(No need to add admin as driver role to see Drivers Page now)
image

### CODE REVIEW

**Review by lindseywn — DISMISSED** [review]
LGTM, functioning properly and tests are all passing

**Review by diyaparm — DISMISSED** [review]
LGTM

File: frontend/src/main/components/Nav/AppNavbar.js [hunk 1]
```diff
@@ -90,14 +90,7 @@ export default function AppNavbar({ currentUser, systemInfo, doLogout, currentUr
...
               {
-                !hasRole(currentUser, "ROLE_DRIVER") && isParticipant(currentUser) && (
-                  <NavDropdown title="Shifts" id="appnavbar-shift-dropdown" data-testid="appnavbar-shift-dropdown" >
-                    <NavDropdown.Item data-testid="appnavbar-shift-dropdown-shifts" as={Link} to="/shift/">Shifts</NavDropdown.Item>
-                  </NavDropdown>
-                )
-              }
-              {
-                hasRole(currentUser, "ROLE_DRIVER") && isParticipant(currentUser) && (
+                (hasRole(currentUser, "ROLE_DRIVER") || hasRole(currentUser, "ROLE_ADMIN")) && isParticipant(currentUser) && (
```
Comment (pconrad) [inline frontend/src/main/components/Nav/AppNavbar.js]: The `isPartcipant(currentUser)` part is redundant if I'm not mistaken.
Couldn't we just say:
```suggestion
                (hasRole(currentUser, "ROLE_DRIVER") || hasRole(currentUser, "ROLE_ADMIN"))  (
```

File: frontend/src/main/components/Nav/AppNavbar.js [hunk 2]
```diff
@@ -120,7 +113,7 @@ export default function AppNavbar({ currentUser, systemInfo, doLogout, currentUr
                 )
               }
               {
-                isParticipant(currentUser) && (
+                (hasRole(currentUser, "ROLE_DRIVER") || hasRole(currentUser, "ROLE_ADMIN")) && isParticipant(currentUser) && (
```
Comment (pconrad) [inline frontend/src/main/components/Nav/AppNavbar.js]: Couldn't we just do:

```suggestion
                (hasRole(currentUser, "ROLE_DRIVER") || hasRole(currentUser, "ROLE_ADMIN")) (
```

**Review by pconrad — CHANGES_REQUESTED** [review]
Two small suggestions for simplifying the code:

**Review by pconrad — CHANGES_REQUESTED** [review]
A couple of small changes to suggest, then this looks good to me.

**Review by pconrad — APPROVED** [review]
LGTM
