### PR TITLE
Anika - Non-Admin Users CanNOT Access Driver List

### LINKED ISSUE #11: BUG: Incorrect backend specification for DriversController
### Summary

Right now any user can get a list of all the drivers and get info on any driver. This is not acceptable.

image

### Expected Behavior

Only admins and drivers should be able to see any relevant info on all the drivers. Users being able to use these endpoints is a significant breach.

### Current / Observed Behavior

Right now anyone can go into swagger and use our endpoint to get all of the drivers.

If someone were to use this maliciously in a production setting, it would be disastrous. 

### Implementation Todos

- [x] Modify `DriversController.java` to no longer allow regular users to use the endpoints.

### PR DESCRIPTION
**Pull request by amisra0**
Anika - Non-admin users now get FORBIDDEN error when trying to access driver list from Swagger UI endpoint.
running npm test and npm run coverage is still 100, everything seems to work and now if you log in as a non-admin user and try to get list of all drivers you will get a 403 FORBIDDEN error. But if you login from an admin account you should get 200 signal and a list of all drivers. So now non-admin users don't have access.
Closes #11

### CODE REVIEW

**Review by yuji-sakaguchi — DISMISSED** [review]
LGTM

File: src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriversController.java [hunk 1]
```diff
@@ -36,7 +36,7 @@ public class DriversController extends ApiController{
     ObjectMapper mapper;
 
     @Operation(summary = "Get a list of all drivers")
-    @PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_DRIVER') || hasRole('ROLE_USER')")
+    @PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_DRIVER')")
```
Comment (pconrad) [inline src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriversController.java:39]: I wonder why there isn't a test for these two cases?

That is: a test that shows that a user that is not a driver and is not an admin gets a 403 Forbidden error when trying to access this endpoint?

**Review by pconrad — CHANGES_REQUESTED** [review]
I'd like to see a test for this in `src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriversControllerTests.java`  

It might look similar to this existing test:

```java
 @Test
  public void users__logged_out_all() throws Exception {
    mockMvc.perform(get("/api/drivers/all"))
        .andExpect(status().is(403));
  }
```


But instead of testing what happens when the user is logged out, it might use the `   @WithMockUser(roles = { "USER" })` annotation. 

You could write the test, then briefly revert the code to the old line, i.e. 
```
@PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_DRIVER') || hasRole('ROLE_USER')")
```
and the test should fail.  Then put in your new line 
```java
@PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_DRIVER')")
```

and the test should pass.

File: src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriversController.java (hunk 1 above)
Comment (amisra0) [reply src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriversController.java:39]: Thank you for the suggestion professor. I have added a test to ensure that a user role gets a 403 error in DriversControllerTests.java

**Review by yuji-sakaguchi — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM
